### PR TITLE
Move websocket headers to opt function 'WithWebsocketHeaders'

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Follow-up up on the discussion in https://github.com/Khan/genqlient/pull/360#pullrequestreview-2471038655.

Move websocket headers to and opt function 'WithWebsocketHeaders'.

I have:
- [x] Written a clear PR title and description (above)
- [x] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [x] Added tests covering my changes, if applicable
- [x] Included a link to the issue fixed, if applicable
- [x] Included documentation, for new features
- [x] Added an entry to the changelog

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@benjaminjkraft Here is a follow-up PR regarding our discussion here: https://github.com/Khan/genqlient/pull/360#pullrequestreview-2471038655

This is without tests now, which is not great. I'm struggling to find an easy way to test this.

Normally I would set up a middleware and set the authentication ctx key for the header. But it seems that the httptest server does not have middleware support out-of-the-box. Maybe I'm wrong?

Could be wise to hold off merging this until tests have been added 🤗

**Comment by benjaminjkraft** [comment]
Thanks!

I think you should be able to do middleware? `gqlgenServer` is just an `http.Handler`, so if you have a middleware that's `func(http.Handler) http.Handler` you can just do `NewServer(middleware(gqlgenServer))`.

**Comment by HaraldNordgren** [comment]
@benjaminjkraft Thanks! Tests added now!

**Review by benjaminjkraft — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
