### PR TITLE
Include __typename on interface-typed fragments

### PR DESCRIPTION
**Pull request by benjaminjkraft**
## Summary:
We ask for `__typename` on interface-typed fields so that we know which
type to use when unmarshaling.  We never strictly need this for
fragments, because the context into which they're spread must either
have `__typename` or must be of concrete type.  But a few cases have
come up where it would be somewhat convenient: first, if you're using
genqlient's types for mocking (not really supported right now, but
possible); and second, for consistency if we add an option to "flatten"
fragments (#30), which would effectively drop the `__typename` field
from the structs otherwise.  Neither is a deeply compelling reason, I
feel, but it's not too hard to do so we may as well.

## Test plan:
make check

### CODE REVIEW

**Review by StevenACoffman — APPROVED** [review]

**Comment by dnerdy** [comment]
I'm not entirely opposed to this change, but it does seem unnecessary. The mock response validation issue was an issue with the way the validator was handling abstract spreads in a concrete context. That's been fixed. That said, if this has utility for mocking in other ways, perhaps we do want it.

**Comment by benjaminjkraft** [comment]
Yeah, there are two ways this is useful:
1. It lets you be a little less careful if you're mixing `js.Obj` and genqlient types in mocks and don't want to match the full genqlient structure exactly.  In practice that's used as a workaround for the fact that marshaling genqlient (output) types doesn't work right with embeds.
2. Once we add an option to "flatten" selections that are just a single fragment-spread (#30), there will be no typename field in the final response struct.  This is fine for genqlient -- it only needs the field in GraphQL and including it in structs was sort of accidental.  But it has proven useful for mocking, if your mock needs to set `__typename`; and it could be helpful for humans to be able to call the method too (although that's hypothetical).
We can talk more this afternoon at our meeting about #108.

**Comment by benjaminjkraft** [comment]
This is on hold for now to see if we need it (see comments on #108).

**Comment by benjaminjkraft** [comment]
This is now replaced by #120, which writes `__typename` when marshaling without any need for the user to fill in a field.

**Pull request closed without merging**
