### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by benjaminjkraft**
It's been quite a while! Let's cut a release. I also added some docs with a checklist, although it's mostly not very interesting.

Test plan: read recent issues

I have:
- [x] Written a clear PR title and description (above)
- [x] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [x] Added tests covering my changes, if applicable
- [x] Included a link to the issue fixed, if applicable
- [x] Included documentation, for new features
- [x] Added an entry to the changelog

### CODE REVIEW

**Comment by benjaminjkraft** [comment]
Since I discussed this in principle with Craig and Steve already, I'm gonna merge it now to avoid merge conflicts!

**Comment by csilvers** [comment]
Love it!

**Comment by StevenACoffman** [comment]
@benjaminjkraft @csilvers I used https://github.com/Khan/genqlient/releases and drafted all prior tags (and including v0.6.0) as releases and only checked v0.6.0 as the latest. As I did so, I told GitHub to autogenerate the release notes. See here:

https://github.com/Khan/genqlient/releases/tag/v0.6.0

This is the process I use for gqlgen and it helps consumers more easily find the latest version, as well as the Changelog. Keeping a Changelog makes it easier for users and contributors to see precisely what notable changes have been made between each release of the project.

I think it would be beneficial if we added drafting GitHub releases to the version release process in this project. If we wanted to script it, this would be the equivalent of what I did for the v0.6.0 release:
```
export VERSION=v0.6.0; gh release create $VERSION --latest --verify-tag --generate-notes --title $VERSION
```

**Comment by benjaminjkraft** [comment]
Cool! I'll add it to the documentation for releases.

**Pull request merged**
