### PR TITLE
Reject operation or argument names that are Go keywords

### LINKED ISSUE #194: Generate fails when building a mutation that takes enum as input.
**Describe the bug**
Generate fails when building a mutation that takes enum as input.

**To Reproduce**
The following fails to generate: 
```graphql
# Schema snippet
enum IPAddressType {
  v4
  v6
}
```
```graphql
# Query snippet
mutation AllocateIpAddress($app: ID!, $region: String, $type: IPAddressType) {
    allocateIpAddress(input: {
        appId: $app,
        region: $region,
        type: $type
    }) {
        app {
            name
        }
    }
}
```
```shell
genqlient internal error: failed to gofmt code:
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)---source code---
```
The following slight change generates without issue: 
```graphql
mutation AllocateIpAddress($app: ID!, $region: String) {
    allocateIpAddress(input: {
        appId: $app,
        region: $region,
        type: v4
    }) {
        app {
            name
        }
    }
}
```

**Expected behavior**
The generator should successfully complete. 

**genqlient version**
0.4.0

### PR DESCRIPTION
**Pull request by benjaminjkraft**
GraphQL is pretty restrictive about its identifiers, so for the most
part we can and do safely use GraphQL identifiers in the Go we generate
with attention only to conflicts with other such identifiers. But we do
need to check one thing, which is that the identifier isn't a Go
keyword. (If it is, the generated code will almost certainly fail to
compile, but often with a confusing error message.) In this commit I add
such checks.

The most likely place to run into trouble here is argument names, which
are often one word and are used as-is.  Operation names, if unexported,
can also be keywords, although in practice they're usually multiword.
Field names are always exported, thus safe.  Generated type names are
always prefixed, camel-cased, with the operation name, so they always
contain an uppercase letter (even if the operation name is lowercase),
but type-names specified by `typename` may collide, so we check those.
In theory we could check type-names specified by `bind`, but these must
be defined by the user, so their code will already fail to compile, so I
didn't bother.  I think that's all the places to consider, although it's
hard to be sure.  In summary, we check argument names, operation names,
and user-specified type names.

Fixes #194.

Test plan: make check

I have:
- [x] Written a clear PR title and description (above)
- [x] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [x] Added tests covering my changes, if applicable
- [x] Included a link to the issue fixed, if applicable
- [x] Included documentation, for new features
- [x] Added an entry to the changelog

### CODE REVIEW

**Review by csilvers — APPROVED** [review]
Good thinking!

So sad I won't be able to use `goto` as a graphql variable name...

**Comment by benjaminjkraft** [comment]
Never fear, you can still use `goTo`!

**Comment by JuanitoFatas** [comment]
Sorry to ask here. I was hitting by this and wonder what if a mutation requires an input that is the same name as Go Keywords (e.g. `type`), is there a way to get around this?

```graphql
mutation Mutation {
  resourceCreate(name: "Test", type: "type-1") {
    resource {
      name
      type
    }
  }
}
```

**Comment by benjaminjkraft** [comment]
That query as written should work, I believe. Of course the query you actually want is probably something like
```graphql
mutation Mutation($name: String, $type: String) {
  resourceCreate(name: $name, type: $type) {
    resource {
      name
      type
    }
  }
}
```
In such a case there's no restriction on the variable name -- you could just as easily name it `$typ` or `$type_`. If you are still having problems, please open a new issue with a reproduction of the problem!

**Pull request merged**
