### PR TITLE
Fix issue where subscription server data channel closing gives error

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Handles errors discussed here: https://github.com/Khan/genqlient/pull/347#issuecomment-2376667291

I have:
- [x] Written a clear PR title and description (above)
- [x] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [x] Added tests covering my changes, if applicable
- [x] Included a link to the issue fixed, if applicable
- [x] Included documentation, for new features
- [x] Added an entry to the changelog

### CODE REVIEW

**Review by benjaminjkraft — COMMENTED** [review]
Seems reasonable to me. It's kinda funny we end up with reflect for this, but it seems fine, and better than adding a bunch of new plumbing to generate a single `close` call.

I'll wait a couple days in case @matthieu4294967296moineau has anything to add.

**Comment by HaraldNordgren** [comment]
Yeah, I don't love the reflect part, although it does solves the problem. The reason I still went with it was because I found the same thing in subscriptionsMap.Unsubscribe().

If we really don't want to reflect then a type cast could likely also solve the problem 🤗

**Comment by benjaminjkraft** [comment]
Ah, I guess it's not the first then!

A cast would be better, but won't work because we don't know the concrete type, right?

**Comment by HaraldNordgren** [comment]
Ah, right!

**Comment by matthieu4294967296moineau** [comment]
> Ah, I guess it's not the first then!
> 
> A cast would be better, but won't work because we don't know the concrete type, right?

yes this is why I used it in a first place to close the channel when unsubscribing

The fix looks good to me, I could test it and it worked fine 👍

**Comment by HaraldNordgren** [comment]
@benjaminjkraft @matthieu4294967296moineau  Great! Thanks for the feedback!

Let's merge? 🚀

**Pull request merged**
