### PR TITLE
Adding more logging for the initial generate setup

### PR DESCRIPTION
**Pull request by thecasual**
I have:
- [X] Written a clear PR title and description (above)
- [X] Signed the [Khan Academy CLA](https://www.khanacademy.org/r/cla)
- [X] Added tests covering my changes, if applicable
- [X] Included a link to the issue fixed, if applicable
- [X] Included documentation, for new features
- [ ] Added an entry to the changelog

### CODE REVIEW

**Review by benjaminjkraft — APPROVED** [review]
Seems reasonable! Ideally we'd have a field for this so we can print it nicely and consistently, I'll add a note to #118.

**Review by benjaminjkraft — CHANGES_REQUESTED** [review]
Whoops, looks like you have some test and lint failures. If you run `UPDATE_SNAPSHOTS=1 make check` locally, and commit the results that should take care of it I think.

**Comment by thecasual** [comment]
I am not sure how to do that apologies. Can you help? Thanks! Also, really enjoying this project as I learn it. There was a few other places I was going to add some documentation for things that I have ran into. I will probably update that as well if that is acceptable for this project :)

**Comment by StevenACoffman** [comment]
> 

Hi @thecasual ! I made a PR against your repository that should fix it for you!

**Comment by StevenACoffman** [comment]
Closed by #246

**Pull request closed without merging**
