### PR TITLE
[🔥AUDIT🔥] Typo fix

### PR DESCRIPTION
**Pull request by benjaminjkraft**
🖍 _This is an audit!_ 🖍

Auditors: steve

### CODE REVIEW

**Comment by StevenACoffman** [comment]
You're hilarious. :) I meant that only as an example. There's a bunch of others here: https://goreportcard.com/report/github.com/Khan/genqlient

```
genqlient/internal/testutil/cupaloy.go
Line 5: warning: exported var Cupaloy should have comment or be unexported (golint)
genqlient/internal/integration/server/server.go
Line 85: warning: exported function RunServer should have comment or be unexported (golint)
genqlient/generate/errors.go
Line 26: warning: if block ends with a return statement, so drop this else and outdent its block (golint)
Line 53: warning: if block ends with a return statement, so drop this else and outdent its block (golint)
genqlient/generate/main.go
Line 39: warning: exported function Main should have comment or be unexported (golint)
genqlient/internal/lint/tools.go
Line 8: warning: a blank import should be only in a main or test package, or have a comment justifying it (golint)
genqlient/internal/testutil/types.go
Line 9: warning: exported type ID should have comment or be unexported (golint)
Line 11: warning: exported type Pokemon should have comment or be unexported (golint)
Line 16: warning: exported method Pokemon.Battle should have comment or be unexported (golint)
Line 20: warning: exported type MyContext should have comment or be unexported (golint)
Line 26: warning: exported function GetClientFromNowhere should have comment or be unexported (golint)
Line 27: warning: exported function GetClientFromContext should have comment or be unexported (golint)
Line 28: warning: exported function GetClientFromMyContext should have comment or be unexported (golint)
genqlient/example/caller.go
Line 22: warning: exported function Main should have comment or be unexported (golint)
genqlient/generate/config.go
Line 18: warning: exported type Config should have comment or be unexported (golint)
Line 148: warning: exported method Config.ValidateAndFillDefaults should have comment or be unexported (golint)
Line 177: warning: exported function ReadAndValidateConfig should have comment or be unexported (golint)
genqlient/generate/genqlient_directive.go
Line 89: warning: exported method GenqlientDirective.GetOmitempty should have comment or be unexported (golint)
Line 90: warning: exported method GenqlientDirective.GetPointer should have comment or be unexported (golint)
```

**Review by StevenACoffman — COMMENTED** [review]
I approve this audit.

**Comment by benjaminjkraft** [comment]
Fixing only the one issue is intentional; see my comments on #96.

**Comment by StevenACoffman** [comment]
Oh great. Thanks. Weird.

**Pull request merged**
